name: Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Transform Data
        run: python src/process_data.py
      - name: Train Models
        run: python src/models.py
      - name: Choose Best Model
        run: python src/model_selection.py
      - name: Train Best Model
        run: python src/train_best_model.py